[versions]
# Android & Kotlin
androidGradlePlugin = "8.2.0"
kotlin = "1.9.10"
ksp = "1.9.10-1.0.13"

# AndroidX Core
coreKtx = "1.13.1"
activityCompose = "1.9.0"
lifecycleRuntimeKtx = "2.8.3"
lifecycleViewmodelCompose = "2.8.3"

# Compose
composeBom = "2024.06.00"
materialIconsExtended = "1.6.8"

# Navigation
navigationCompose = "2.7.7"

# Coroutines
kotlinxCoroutinesAndroid = "1.7.3"

# Image Loading
coilCompose = "2.6.0"
coilGif = "2.6.0"

# Room
room = "2.6.1"

# Testing - Unit
junit = "4.13.2"

# Testing - Instrumented
junitVersion = "1.2.1"
androidxTestCore = "1.6.1"
androidxTestRunner = "1.6.2"
androidxTestRules = "1.6.1"
androidxTestExtJunit = "1.2.1"
androidxEspressoCore = "3.6.1"
androidxTestOrchestrator = "1.5.0"

# Mockk y Kotest
mockk = "1.13.10"
kotest = "5.8.0"
coroutinesTest = "1.7.3"

[libraries]
# AndroidX Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIconsExtended" }

# Navigation
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# Coroutines
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }

# Image Loading
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coilGif" }

# Room Database
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Testing - Unit Tests
junit = { group = "junit", name = "junit", version.ref = "junit" }

# Testing - Instrumented Tests
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "androidxTestCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
androidx-test-orchestrator = { group = "androidx.test", name = "orchestrator", version.ref = "androidxTestOrchestrator" }

# Testing - Espresso
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspressoCore" }

# Testing - Compose UI Tests
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

# Mockk
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }

# Kotest
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }

# Coroutines Test
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }